language: python

matrix:
  include:
  - python: '3.6'
  - python: '3.7'
  - python: '3.8'
  - python: '3.9'

before_install:
  - pip install --upgrade pip setuptools
  - pip install --upgrade flake8 flake8-import-order
  # - pip install --upgrade pytest
  # - pip install --upgrade git+https://github.com/streamlink/streamlink.git

install:
  - pip install --upgrade -e .

script:
  - liveproxy --version
  # - pytest
  - flake8
